### ISSUE TITLE
Normalizr `arrayOf` should pass a object instead of string

### ISSUE THREAD

**Issue by TryingToImprove** [tayiorbeii/egghead.io_idiomatic_redux_course_notes#2]
In https://github.com/tayiorbeii/egghead.io_idiomatic_redux_course_notes/blob/master/26-Normalizing_API_Responses_with_normalizr.md the `arrayOfTodos` uses a string, **but** it should use the `todo` object instead otherwise normalizr will throw a error. _(Uncaught Error: ArraySchema requires item schema to be an object.)_ 

Great repository btw.. :+1:

**Comment by tayiorbeii** [comment]
@TryingToImprove Thanks for the note :) I just merged a PR that fixes this. 😎
